services:
  icecast:
    image: libretime/icecast:2.4.4
    container_name: radio_icecast
    volumes:
      - ./icecast.xml:/etc/icecast2/icecast.xml:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20

  mpd:
    build: ./mpd
    container_name: radio_mpd
    depends_on:
      icecast:
        condition: service_healthy
    environment:
      - MPD_MUSIC=/music
    volumes:
      - ./music:/music:ro
      - mpd-data:/var/lib/mpd
      - mpd-playlists:/playlists
    # TEMP: expose to host to test quickly; remove later if you want
    ports:
      - "6600:6600"
    restart: unless-stopped
    healthcheck:
      # don’t rely on mpc; just check the port
      test: ["CMD-SHELL", "nc -z localhost 6600 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30

  ympd:
    image: giof71/ympd:latest
    container_name: radio_ympd
    depends_on:
      mpd:
        condition: service_healthy
    environment:
      - YMPD_MPD_SERVER=mpd
      - YMPD_MPD_PORT=6600
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  mpd-data:
  mpd-playlists:
